[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-sys-tuner"
description = "The miraland cluster system tuner daemon"
version = "1.14.17"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
libc = "0.2.126"
log = "0.4.17"
miraland-logger = { path = "../logger", version = "1.14.17" }
miraland-version = { path = "../version", version = "1.14.17" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.24.2"
sysctl = "0.4.4"

[lib]
name = "miraland_sys_tuner"

[[bin]]
name = "miraland-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
