[package]
name = "miraland-config-program"
description = "Miraland Config program"
documentation = "https://docs.rs/miraland-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }

[dev-dependencies]
miraland-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
