[package]
name = "miraland-config-program"
version = "1.14.17-rc3"
description = "Miraland Config program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
miraland-program-runtime = { path = "../../program-runtime", version = "=1.14.17-rc3" }
miraland-sdk = { path = "../../sdk", version = "=1.14.17-rc3" }
serde = "1.0.138"
serde_derive = "1.0.103"

[dev-dependencies]
miraland-logger = { path = "../../logger", version = "=1.14.17-rc3" }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
