[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-net-shaper"
description = "The miraland cluster network shaping tool"
version = "1.14.17"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
miraland-logger = { path = "../logger", version = "1.14.17" }
rand = "0.7.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.81"

[[bin]]
name = "miraland-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
