[package]
name = "miraland-cargo-build-bpf"
version = "1.14.19"
description = "Compile a local package and all of its dependencies using the Miraland SBF SDK"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
miraland-sdk = { path = "..", version = "1.14.19" }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
