[package]
name = "miraland-ed25519-program-tests"
version = "1.14.17-rc5"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
miraland-program-test = { path = "../../program-test", version = "=1.14.17-rc5" }
miraland-sdk = { path = "../../sdk", version = "=1.14.17-rc5" }
rand = "0.7.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
