[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "miraland-local-cluster"
description = "Blockchain for community beyond the horizon"
version = "1.14.17-rc1"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-local-cluster"

[dependencies]
crossbeam-channel = "0.5"
fs_extra = "1.2.0"
itertools = "0.10.3"
log = "0.4.17"
miraland-client = { path = "../client", version = "=1.14.17-rc1" }
miraland-config-program = { path = "../programs/config", version = "=1.14.17-rc1" }
miraland-core = { path = "../core", version = "=1.14.17-rc1" }
miraland-entry = { path = "../entry", version = "=1.14.17-rc1" }
miraland-gossip = { path = "../gossip", version = "=1.14.17-rc1" }
miraland-ledger = { path = "../ledger", version = "=1.14.17-rc1" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc1" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc1" }
miraland-stake-program = { path = "../programs/stake", version = "=1.14.17-rc1" }
miraland-streamer = { path = "../streamer", version = "=1.14.17-rc1" }
miraland-vote-program = { path = "../programs/vote", version = "=1.14.17-rc1" }
rand = "0.7.0"
rayon = "1.5.3"
tempfile = "3.3.0"

[dev-dependencies]
assert_matches = "1.5.0"
gag = "1.0.0"
miraland-download-utils = { path = "../download-utils", version = "=1.14.17-rc1" }
miraland-logger = { path = "../logger", version = "=1.14.17-rc1" }
serial_test = "0.8.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
