[package]
name = "miraland-vote"
description = "Miraland vote"
documentation = "https://docs.rs/miraland-vote"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
miraland-frozen-abi = { workspace = true }
miraland-frozen-abi-macro = { workspace = true }
miraland-sdk = { workspace = true }
miraland-vote-program = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_vote"

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }

[features]
dev-context-only-utils = []
