[package]
name = "miraland-bpf-rust-error-handling"
version = "1.14.17"
description = "Miraland BPF test program written in Rust"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-bpf-rust-error-handling"
edition = "2021"

[dependencies]
miraland-program = { path = "../../../../sdk/program", version = "1.14.17" }
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
