[package]
name = "miraland-sbf-rust-simulation"
description = "Miraland SBF Program Simulation Differences"
documentation = "https://docs.rs/miraland-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
miraland-program = { workspace = true }

[dev-dependencies]
miraland-logger = { workspace = true }
miraland-program-test = { workspace = true }
miraland-sdk = { workspace = true }
miraland-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
