[package]
name = "miraland-version"
version = "1.14.17"
description = "Solana Version"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/miraland-version"
edition = "2021"

[dependencies]
log = "0.4.17"
semver = "1.0.10"
serde = "1.0.138"
serde_derive = "1.0.103"
solana-frozen-abi = { path = "../frozen-abi", version = "=1.14.17" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.14.17" }
solana-sdk = { path = "../sdk", version = "=1.14.17" }

[lib]
name = "miraland_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
