[package]
name = "miraland-keygen"
version = "1.14.17-rc4"
description = "Miraland key generation utility"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-keygen"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
clap = { version = "3.1.5", features = ["cargo"] }
dirs-next = "2.0.0"
miraland-clap-v3-utils = { path = "../clap-v3-utils", version = "=1.14.17-rc4" }
miraland-cli-config = { path = "../cli-config", version = "=1.14.17-rc4" }
miraland-remote-wallet = { path = "../remote-wallet", version = "=1.14.17-rc4" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc4" }
miraland-version = { path = "../version", version = "=1.14.17-rc4" }
num_cpus = "1.13.1"
tiny-bip39 = "0.8.2"

[[bin]]
name = "miraland-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
