[package]
name = "miraland-stake-program"
description = "Miraland Stake program"
documentation = "https://docs.rs/miraland-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
miraland-config-program = { workspace = true }
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
miraland-logger = { workspace = true }
proptest = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
