[package]
name = "miraland-rpc"
description = "Miraland RPC"
documentation = "https://docs.rs/miraland-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
miraland-account-decoder = { workspace = true }
miraland-accounts-db = { workspace = true }
miraland-client = { workspace = true }
miraland-entry = { workspace = true }
miraland-faucet = { workspace = true }
miraland-gossip = { workspace = true }
miraland-ledger = { workspace = true }
miraland-measure = { workspace = true }
miraland-metrics = { workspace = true }
miraland-perf = { workspace = true }
miraland-poh = { workspace = true }
miraland-rayon-threadlimit = { workspace = true }
miraland-rpc-client-api = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-send-transaction-service = { workspace = true }
miraland-stake-program = { workspace = true }
miraland-storage-bigtable = { workspace = true }
miraland-streamer = { workspace = true }
miraland-tpu-client = { workspace = true }
miraland-transaction-status = { workspace = true }
miraland-version = { workspace = true }
miraland-vote = { workspace = true }
miraland-vote-program = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
solarti-token = { workspace = true, features = ["no-entrypoint"] }
solarti-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
miraland-net-utils = { workspace = true }
miraland-stake-program = { workspace = true }
serial_test = { workspace = true }
solarti-pod = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "miraland_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
