[package]
name = "miraland-cargo-build-sbf"
version = "1.14.17"
description = "Compile a local package and all of its dependencies using the Solana SBF SDK"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.4"
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
log = { version = "0.4.14", features = ["std"] }
miraland-download-utils = { path = "../../download-utils", version = "1.14.17" }
miraland-logger = { path = "../../logger", version = "1.14.17" }
miraland-sdk = { path = "..", version = "1.14.17" }
regex = "1.5.6"
tar = "0.4.38"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-sbf"
path = "src/main.rs"
