[package]
name = "miraland-sbf-rust-curve25519"
documentation = "https://docs.rs/miraland-sbf-rust-zktoken_crypto"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
miraland-program = { workspace = true }
miraland-zk-token-sdk = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
