[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-transaction-dos"
version = "1.14.17-rc6"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
publish = false

[dependencies]
bincode = "1.3.3"
clap = "2.33.1"
log = "0.4.17"
miraland-clap-utils = { path = "../clap-utils", version = "=1.14.17-rc6" }
miraland-cli = { path = "../cli", version = "=1.14.17-rc6" }
miraland-client = { path = "../client", version = "=1.14.17-rc6" }
miraland-core = { path = "../core", version = "=1.14.17-rc6" }
miraland-faucet = { path = "../faucet", version = "=1.14.17-rc6" }
miraland-gossip = { path = "../gossip", version = "=1.14.17-rc6" }
miraland-logger = { path = "../logger", version = "=1.14.17-rc6" }
miraland-measure = { path = "../measure", version = "=1.14.17-rc6" }
miraland-net-utils = { path = "../net-utils", version = "=1.14.17-rc6" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc6" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc6" }
miraland-streamer = { path = "../streamer", version = "=1.14.17-rc6" }
miraland-transaction-status = { path = "../transaction-status", version = "=1.14.17-rc6" }
miraland-version = { path = "../version", version = "=1.14.17-rc6" }
rand = "0.7.0"
rayon = "1.5.3"

[dev-dependencies]
miraland-local-cluster = { path = "../local-cluster", version = "=1.14.17-rc6" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
