[package]
name = "miraland-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
miraland-clap-utils = { workspace = true }
miraland-cli = { workspace = true }
miraland-client = { workspace = true }
miraland-core = { workspace = true }
miraland-faucet = { workspace = true }
miraland-gossip = { workspace = true }
miraland-logger = { workspace = true }
miraland-measure = { workspace = true }
miraland-net-utils = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-streamer = { workspace = true }
miraland-transaction-status = { workspace = true }
miraland-version = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
miraland-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
