[package]
name = "miraland-bpf-rust-param-passing-dep"
version = "1.14.17-rc3"
description = "Miraland BPF program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-bpf-rust-param-passing-dep"
edition = "2021"

[dependencies]
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
