[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-validator"
description = "Blockchain for community beyond the horizon"
version = "1.14.19"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-validator"
default-run = "miraland-validator"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
fd-lock = "3.0.12"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils = "18.0.0"
log = "0.4.17"
miraland-clap-utils = { path = "../clap-utils", version = "1.14.19" }
miraland-cli-config = { path = "../cli-config", version = "1.14.19" }
miraland-client = { path = "../client", version = "1.14.19" }
miraland-core = { path = "../core", version = "1.14.19" }
miraland-download-utils = { path = "../download-utils", version = "1.14.19" }
miraland-entry = { path = "../entry", version = "1.14.19" }
miraland-faucet = { path = "../faucet", version = "1.14.19" }
miraland-genesis-utils = { path = "../genesis-utils", version = "1.14.19" }
miraland-gossip = { path = "../gossip", version = "1.14.19" }
miraland-ledger = { path = "../ledger", version = "1.14.19" }
miraland-logger = { path = "../logger", version = "1.14.19" }
miraland-metrics = { path = "../metrics", version = "1.14.19" }
miraland-net-utils = { path = "../net-utils", version = "1.14.19" }
miraland-perf = { path = "../perf", version = "1.14.19" }
miraland-poh = { path = "../poh", version = "1.14.19" }
miraland-rpc = { path = "../rpc", version = "1.14.19" }
miraland-runtime = { path = "../runtime", version = "1.14.19" }
miraland-sdk = { path = "../sdk", version = "1.14.19" }
miraland-send-transaction-service = { path = "../send-transaction-service", version = "1.14.19" }
miraland-storage-bigtable = { path = "../storage-bigtable", version = "1.14.19" }
miraland-streamer = { path = "../streamer", version = "1.14.19" }
miraland-test-validator = { path = "../test-validator", version = "1.14.19" }
miraland-version = { path = "../version", version = "1.14.19" }
miraland-vote-program = { path = "../programs/vote", version = "1.14.19" }
num_cpus = "1.13.1"
rand = "0.7.0"
# rustix = "0.37.23" # MI
serde = "1.0.138"
serde_json = "1.0.81"
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[target."cfg(unix)".dependencies]
libc = "0.2.141"
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
