[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-merkle-root-bench"
version = "1.14.17-rc4"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.17"
miraland-logger = { path = "../logger", version = "=1.14.17-rc4" }
miraland-measure = { path = "../measure", version = "=1.14.17-rc4" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc4" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc4" }
miraland-version = { path = "../version", version = "=1.14.17-rc4" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
