[package]
name = "solana-bpf-rust-secp256k1-recover"
version = "1.14.17-rc1"
description = "Miraland BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/solana-bpf-rust-secp256k1-recover"
edition = "2021"

[dependencies]
libsecp256k1 = { version = "0.7.0", default-features = false }
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc1" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
