[package]
name = "miraland-bpf-rust-sanity"
version = "1.14.17-rc7"
description = "Miraland BPF test program written in Rust"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-bpf-rust-sanity"
edition = "2021"

[features]
test-bpf = []

[dependencies]
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc7" }

[dev-dependencies]
miraland-program-runtime = { path = "../../../../program-runtime", version = "=1.14.17-rc7" }
miraland-program-test = { path = "../../../../program-test", version = "=1.14.17-rc7" }
miraland-sdk = { path = "../../../../sdk", version = "=1.14.17-rc7" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
