[package]
name = "miraland-address-lookup-table-program"
version = "1.14.17-rc7"
description = "Miraland address lookup table program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-address-loookup-table-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytemuck = "1.11.0"
log = "0.4.17"
miraland-frozen-abi = { path = "../../frozen-abi", version = "=1.14.17-rc7" }
miraland-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.14.17-rc7" }
miraland-program = { path = "../../sdk/program", version = "=1.14.17-rc7" }
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.138", features = ["derive"] }
thiserror = "1.0"

[target.'cfg(not(target_os = "solana"))'.dependencies]
miraland-program-runtime = { path = "../../program-runtime", version = "=1.14.17-rc7" }
miraland-sdk = { path = "../../sdk", version = "=1.14.17-rc7" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
