[package]
name = "miraland-bpf-rust-rand"
version = "1.14.17-rc4"
description = "Miraland BPF test program written in Rust"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-bpf-rust-rand"
edition = "2021"

[dependencies]
getrandom = { version = "0.1.14", features = ["dummy"] }
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc4" }
rand = "0.7"

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
