[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "miraland-gossip"
description = "Blockchain for community beyond the horizon"
version = "1.14.17-rc1"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-gossip"

[dependencies]
bincode = "1.3.3"
bv = { version = "0.11.1", features = ["serde"] }
clap = "2.33.1"
crossbeam-channel = "0.5"
flate2 = "1.0"
indexmap = { version = "1.9", features = ["rayon"] }
itertools = "0.10.3"
log = "0.4.17"
lru = "0.7.7"
matches = "0.1.9"
miraland-bloom = { path = "../bloom", version = "=1.14.17-rc1" }
miraland-clap-utils = { path = "../clap-utils", version = "=1.14.17-rc1" }
miraland-client = { path = "../client", version = "=1.14.17-rc1" }
miraland-entry = { path = "../entry", version = "=1.14.17-rc1" }
miraland-frozen-abi = { path = "../frozen-abi", version = "=1.14.17-rc1" }
miraland-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.14.17-rc1" }
miraland-ledger = { path = "../ledger", version = "=1.14.17-rc1" }
miraland-logger = { path = "../logger", version = "=1.14.17-rc1" }
miraland-measure = { path = "../measure", version = "=1.14.17-rc1" }
miraland-metrics = { path = "../metrics", version = "=1.14.17-rc1" }
miraland-net-utils = { path = "../net-utils", version = "=1.14.17-rc1" }
miraland-perf = { path = "../perf", version = "=1.14.17-rc1" }
miraland-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.14.17-rc1" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc1" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc1" }
miraland-streamer = { path = "../streamer", version = "=1.14.17-rc1" }
miraland-version = { path = "../version", version = "=1.14.17-rc1" }
miraland-vote-program = { path = "../programs/vote", version = "=1.14.17-rc1" }
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.3"
serde = "1.0.138"
serde_bytes = "0.11"
serde_derive = "1.0.103"
thiserror = "1.0"

[dev-dependencies]
num_cpus = "1.13.1"
regex = "1"
serial_test = "0.8.0"

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "miraland-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
