[package]
name = "miraland-compute-budget-program"
description = "Miraland Compute Budget program"
documentation = "https://docs.rs/miraland-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
