[package]
name = "miraland-compute-budget-program"
description = "Miraland Compute Budget program"
version = "1.14.17-rc1"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-compute-budget-program"
repository = "https://github.com/miraland-labs/miraland"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
miraland-program-runtime = { path = "../../program-runtime", version = "=1.14.17-rc1" }
miraland-sdk = { path = "../../sdk", version = "=1.14.17-rc1" }

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
