[package]
name = "miraland-transaction-status"
version = "1.14.17-rc3"
description = "Miraland transaction status types"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-transaction-status"
license = "Apache-2.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
base64 = "0.13.0"
bincode = "1.3.3"
borsh = "0.9.1"
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
miraland-account-decoder = { path = "../account-decoder", version = "=1.14.17-rc3" }
miraland-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.14.17-rc3" }
miraland-measure = { path = "../measure", version = "=1.14.17-rc3" }
miraland-metrics = { path = "../metrics", version = "=1.14.17-rc3" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc3" }
miraland-vote-program = { path = "../programs/vote", version = "=1.14.17-rc3" }
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
solarti-associated-token-account = { version = "=1.1.4", features = ["no-entrypoint"] }
solarti-memo = { version = "=3.0.2", features = ["no-entrypoint"] }
solarti-token = { version = "=3.5.1", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "=0.6.2", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
