[package]
name = "miraland-transaction-status"
version = "1.14.18"
description = "Miraland transaction status types"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-transaction-status"
license = "Apache-2.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
base64 = "0.13.0"
bincode = "1.3.3"
borsh = "0.10.3"
# NOTE: Use the workspace version once solarti-associated-token-account uses borsh 0.10.
borsh0-9 = { package = "borsh", version = "0.9.3" }
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
miraland-account-decoder = { path = "../account-decoder", version = "1.14.18" }
miraland-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "1.14.18" }
miraland-measure = { path = "../measure", version = "1.14.18" }
miraland-metrics = { path = "../metrics", version = "1.14.18" }
miraland-sdk = { path = "../sdk", version = "1.14.18" }
miraland-vote-program = { path = "../programs/vote", version = "1.14.18" }
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
solarti-associated-token-account = { version = "1.1", features = ["no-entrypoint"] }
solarti-memo = { version = "3.0", features = ["no-entrypoint"] }
solarti-token = { version = "3.5", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "0.6", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
