[package]
name = "solana-bpf-rust-realloc"
version = "1.14.17-rc1"
description = "Solana BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/solana-bpf-rust-realloc"
edition = "2021"

[features]
default = ["program"]
program = []

[dependencies]
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc1" }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
