# This package only exists to avoid circular dependencies during cargo publish:
# miraland-bpf-loader-program -> miraland-program-test -> miraland-bpf-loader-program

[package]
name = "miraland-bpf-loader-program-tests"
version = "1.14.18"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
miraland-bpf-loader-program = { path = "../bpf_loader", version = "1.14.18" }
miraland-program-test = { path = "../../program-test", version = "1.14.18" }
miraland-sdk = { path = "../../sdk", version = "1.14.18" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
