[package]
name = "miraland-loader-v4-program"
description = "Miraland Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
miraland-measure = { workspace = true }
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }
solana_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "miraland_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
