[package]
name = "miraland-program-runtime"
version = "1.14.17"
description = "Miraland program runtime"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-program-runtime"
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
eager = "0.1.0"
itertools =  "0.10.1"
libc = "=0.2.126"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
rand = "0.7.0"
serde = { version = "1.0.129", features = ["derive", "rc"] }
miraland-frozen-abi = { path = "../frozen-abi", version = "1.14.17" }
miraland-frozen-abi-macro = { path = "../frozen-abi/macro", version = "1.14.17" }
miraland-measure = { path = "../measure", version = "1.14.17" }
miraland-metrics = { path = "../metrics", version = "1.14.17" }
miraland-sdk = { path = "../sdk", version = "1.14.17" }
thiserror = "1.0"
enum-iterator = "0.8.1"

[dev-dependencies]
miraland-logger = { path = "../logger", version = "1.14.17" }

[lib]
crate-type = ["lib"]
name = "solana_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
