[package]
name = "miraland-udp-client"
description = "Miraland UDP Client"
documentation = "https://docs.rs/miraland-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
miraland-connection-cache = { workspace = true }
miraland-net-utils = { workspace = true }
miraland-sdk = { workspace = true }
miraland-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
