[package]
name = "miraland-notifier"
version = "1.14.17-rc7"
description = "Miraland Notifier"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-notifier"
edition = "2021"

[dependencies]
h2 = "=0.3.20"
log = "0.4.17"
reqwest = { version = "=0.11.11", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "miraland_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
