[package]
name = "miraland-stake-accounts"
description = "Blockchain for community beyond the horizon"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
version = "1.14.17-rc6"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-stake-accounts"

[dependencies]
clap = "2.33.1"
miraland-clap-utils = { path = "../clap-utils", version = "=1.14.17-rc6" }
miraland-cli-config = { path = "../cli-config", version = "=1.14.17-rc6" }
miraland-client = { path = "../client", version = "=1.14.17-rc6" }
miraland-remote-wallet = { path = "../remote-wallet", version = "=1.14.17-rc6" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc6" }
miraland-stake-program = { path = "../programs/stake", version = "=1.14.17-rc6" }

[dev-dependencies]
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc6" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
