[package]
name = "miraland-tokens"
description = "Blockchain for community beyond the horizon"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.14.17-rc3"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.1.6"
ctrlc = { version = "3.2.2", features = ["termination"] }
indexmap = "1.9.1"
indicatif = "0.16.2"
miraland-account-decoder = { path = "../account-decoder", version = "=1.14.17-rc3" }
miraland-clap-utils = { path = "../clap-utils", version = "=1.14.17-rc3" }
miraland-cli-config = { path = "../cli-config", version = "=1.14.17-rc3" }
miraland-client = { path = "../client", version = "=1.14.17-rc3" }
miraland-remote-wallet = { path = "../remote-wallet", version = "=1.14.17-rc3" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc3" }
miraland-transaction-status = { path = "../transaction-status", version = "=1.14.17-rc3" }
miraland-version = { path = "../version", version = "=1.14.17-rc3" }
pickledb = { version = "0.5.1", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
solarti-associated-token-account = { version = "=1.1.3" }
solarti-token = { version = "=3.5.0", features = ["no-entrypoint"] }
tempfile = "3.3.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
miraland-logger = { path = "../logger", version = "=1.14.17-rc3" }
miraland-streamer = { path = "../streamer", version = "=1.14.17-rc3" }
miraland-test-validator = { path = "../test-validator", version = "=1.14.17-rc3" }
