[package]
name = "miraland-quic-client"
description = "Miraland Quic Client"
documentation = "https://docs.rs/miraland-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
miraland-connection-cache = { workspace = true }
miraland-measure = { workspace = true }
miraland-metrics = { workspace = true }
miraland-net-utils = { workspace = true }
miraland-rpc-client-api = { workspace = true }
miraland-sdk = { workspace = true }
miraland-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
miraland-logger = { workspace = true }
miraland-perf = { workspace = true }
