[package]
name = "miraland-ledger"
version = "1.14.17-rc7"
description = "Miraland ledger"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-ledger"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
bitflags = "1.3.1"
byteorder = "1.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
chrono-humanize = "0.2.1"
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
fs_extra = "1.2.0"
futures = "0.3.21"
itertools = "0.10.3"
lazy_static = "1.4.0"
libc = "0.2.126"
log = { version = "0.4.17" }
lru = "0.7.7"
miraland-account-decoder = { path = "../account-decoder", version = "=1.14.17-rc7" }
miraland-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.14.17-rc7" }
miraland-entry = { path = "../entry", version = "=1.14.17-rc7" }
miraland-frozen-abi = { path = "../frozen-abi", version = "=1.14.17-rc7" }
miraland-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.14.17-rc7" }
miraland-measure = { path = "../measure", version = "=1.14.17-rc7" }
miraland-metrics = { path = "../metrics", version = "=1.14.17-rc7" }
miraland-perf = { path = "../perf", version = "=1.14.17-rc7" }
miraland-program-runtime = { path = "../program-runtime", version = "=1.14.17-rc7" }
miraland-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.14.17-rc7" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc7" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc7" }
miraland-stake-program = { path = "../programs/stake", version = "=1.14.17-rc7" }
miraland-storage-bigtable = { path = "../storage-bigtable", version = "=1.14.17-rc7" }
miraland-storage-proto = { path = "../storage-proto", version = "=1.14.17-rc7" }
miraland-transaction-status = { path = "../transaction-status", version = "=1.14.17-rc7" }
miraland-vote-program = { path = "../programs/vote", version = "=1.14.17-rc7" }
num_cpus = "1.13.1"
num_enum = "0.5.7"
prost = "0.11.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.3"
reed-solomon-erasure = { version = "6.0.0", features = ["simd-accel"] }
serde = "1.0.138"
serde_bytes = "0.11.6"
sha2 = "0.10.2"
solarti-token = { version = "3.5", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "0.6", features = ["no-entrypoint"] }
static_assertions = "1.1.0"
tempfile = "3.3.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
trees = "0.4.2"

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
version = "0.19.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
bs58 = "0.4.0"
matches = "0.1.9"
miraland-account-decoder = { path = "../account-decoder", version = "=1.14.17-rc7" }
miraland-logger = { path = "../logger", version = "=1.14.17-rc7" }
test-case = "2.1.0"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "miraland_ledger"

[[bench]]
name = "sigverify_shreds"

[[bench]]
name = "blockstore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
