[package]
name = "miraland-storage-proto"
version = "1.14.18"
description = "Miraland Storage Protobuf Definitions"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.com>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-storage-proto"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
miraland-account-decoder = { path = "../account-decoder", version = "1.14.18" }
miraland-sdk = { path = "../sdk", version = "1.14.18" }
miraland-transaction-status = { path = "../transaction-status", version = "1.14.18" }
prost = "0.11.0"
serde = "1.0.138"

[dev-dependencies]
enum-iterator = "0.8.1"

[lib]
crate-type = ["lib"]
name = "solana_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
petgraph = "0.6.3"
tonic-build = "0.8.0"

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = "1.0.5"
