[package]
name = "miraland-logger"
version = "1.14.17-rc7"
description = "Miraland Logger"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-logger"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.17"

[lib]
name = "miraland_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
