[package]
name = "miraland-rayon-threadlimit"
version = "1.14.17-rc4"
description = "miraland-rayon-threadlimit"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/miraland-labs/miraland"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num_cpus = "1.13.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
