[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-geyser-plugin-interface"
description = "The Miraland Geyser plugin interface."
version = "1.14.19"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-geyser-plugin-interface"

[dependencies]
log = "0.4.17"
miraland-sdk = { path = "../sdk", version = "1.14.19" }
miraland-transaction-status = { path = "../transaction-status", version = "1.14.19" }
thiserror = "1.0.31"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
