[package]
name = "miraland-frozen-abi-macro"
version = "1.14.17-rc7"
description = "Miraland Frozen ABI Macro"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-frozen-abi-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits", "visit-mut"] }

[build-dependencies]
rustc_version = "0.4"
