[package]
name = "miraland-runtime-transaction"
description = "Miraland runtime-transaction"
documentation = "https://docs.rs/miraland-runtime-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib"]
name = "miraland_runtime_transaction"

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }
miraland-program ={ workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
