[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-geyser-plugin-postgres"
description = "The Solana AccountsDb plugin for PostgreSQL database."
version = "1.14.7"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-validator"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs58 = "0.4.0"
bytemuck = "1.11.0"
chrono = { version = "0.4.11", features = ["serde"] }
crossbeam-channel = "0.5"
log = "0.4.17"
openssl = { version = "0.10" }
postgres = { version = "0.19.4", features = ["with-chrono-0_4"] }
postgres-types = { version = "0.2.4", features = ["derive"] }
postgres-openssl = { version = "0.5.0"}
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
solana-geyser-plugin-interface = { path = "../geyser-plugin-interface", version = "=1.14.7" }
solana-logger = { path = "../logger", version = "=1.14.7" }
solana-measure = { path = "../measure", version = "=1.14.7" }
solana-metrics = { path = "../metrics", version = "=1.14.7" }
solana-runtime = { path = "../runtime", version = "=1.14.7" }
solana-sdk = { path = "../sdk", version = "=1.14.7" }
solana-transaction-status = { path = "../transaction-status", version = "=1.14.7" }
thiserror = "1.0.31"
tokio-postgres = "0.7.7"

[dev-dependencies]
libc = "0.2.126"
libloading = "0.7.3"
serial_test = "0.8.0"
socket2 = { version = "0.4.4", features = ["all"] }

solana-account-decoder = { path = "../account-decoder", version = "=1.14.7" }
solana-core = { path = "../core", version = "=1.14.7" }
solana-local-cluster = { path = "../local-cluster", version = "=1.14.7" }
solana-net-utils = { path = "../net-utils", version = "=1.14.7" }
solana-streamer = { path = "../streamer", version = "=1.14.7" }
tempfile = "3.3.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
