[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-geyser-plugin-postgres"
description = "The Miraland AccountsDb plugin for PostgreSQL database."
version = "1.14.17"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-validator"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs58 = "0.4.0"
bytemuck = "1.11.0"
chrono = { version = "=0.4.26", features = ["serde"] }
crossbeam-channel = "0.5"
log = "0.4.17"
miraland-geyser-plugin-interface = { path = "../geyser-plugin-interface", version = "1.14.17" }
miraland-logger = { path = "../logger", version = "1.14.17" }
miraland-measure = { path = "../measure", version = "1.14.17" }
miraland-metrics = { path = "../metrics", version = "1.14.17" }
miraland-runtime = { path = "../runtime", version = "1.14.17" }
miraland-sdk = { path = "../sdk", version = "1.14.17" }
miraland-transaction-status = { path = "../transaction-status", version = "1.14.17" }
openssl = { version = "0.10" }
postgres = { version = "0.19.4", features = ["with-chrono-0_4"] }
postgres-openssl = { version = "0.5.0" }
postgres-types = { version = "0.2.4", features = ["derive"] }
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio-postgres = "0.7.7"

[dev-dependencies]
libc = "=0.2.141"
libloading = "0.7.3"

miraland-account-decoder = { path = "../account-decoder", version = "1.14.17" }
miraland-core = { path = "../core", version = "1.14.17" }
miraland-local-cluster = { path = "../local-cluster", version = "1.14.17" }
miraland-net-utils = { path = "../net-utils", version = "1.14.17" }
miraland-streamer = { path = "../streamer", version = "1.14.17" }
serial_test = "0.8.0"
socket2 = { version = "0.4.4", features = ["all"] }
tempfile = "=3.6.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
