# This package only exists to avoid circular dependencies during cargo publish:
# miraland-runtime -> miraland-address-program -> miraland-program-test -> miraland-runtime

[package]
name = "miraland-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
miraland-address-lookup-table-program = { workspace = true }
miraland-program-test = { workspace = true }
miraland-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
