# This package only exists to avoid circular dependencies during cargo publish:
# miraland-runtime -> miraland-address-program -> miraland-program-test -> miraland-runtime

[package]
name = "miraland-address-lookup-table-program-tests"
version = "1.14.17-rc7"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
miraland-address-lookup-table-program = { path = "../address-lookup-table", version = "=1.14.17-rc7" }
miraland-program-test = { path = "../../program-test", version = "=1.14.17-rc7" }
miraland-sdk = { path = "../../sdk", version = "=1.14.17-rc7" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
