[package]
name = "miraland-test-validator"
description = "Blockchain for community beyond the horizon"
version = "1.14.17-rc5"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-test-validator"
readme = "../README.md"
repository = "https://github.com/miraland-labs/miraland"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
log = "0.4.17"
miraland-cli-output = { path = "../cli-output", version = "=1.14.17-rc5" }
miraland-client = { path = "../client", version = "=1.14.17-rc5" }
miraland-core = { path = "../core", version = "=1.14.17-rc5" }
miraland-gossip = { path = "../gossip", version = "=1.14.17-rc5" }
miraland-ledger = { path = "../ledger", version = "=1.14.17-rc5" }
miraland-logger = { path = "../logger", version = "=1.14.17-rc5" }
miraland-net-utils = { path = "../net-utils", version = "=1.14.17-rc5" }
miraland-program-runtime = { path = "../program-runtime", version = "=1.14.17-rc5" }
miraland-program-test = { path = "../program-test", version = "=1.14.17-rc5" }
miraland-rpc = { path = "../rpc", version = "=1.14.17-rc5" }
miraland-runtime = { path = "../runtime", version = "=1.14.17-rc5" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc5" }
miraland-streamer = { path = "../streamer", version = "=1.14.17-rc5" }
serde_derive = "1.0.103"
serde_json = "1.0.81"
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
