[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-ledger-tool"
description = "Blockchain for community beyond the horizon"
version = "1.14.18"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-ledger-tool"

[dependencies]
base64 = "0.13.0"
chrono = "=0.4.26"
clap = "2.33.1"
crossbeam-channel = "0.5"
csv = "1.1.6"
dashmap = "4.0.2"
histogram = "0.6.9"
itertools = "0.10.3"
log = { version = "0.4.17" }
miraland-clap-utils = { path = "../clap-utils", version = "1.14.18" }
miraland-cli-output = { path = "../cli-output", version = "1.14.18" }
miraland-core = { path = "../core", version = "1.14.18" }
miraland-entry = { path = "../entry", version = "1.14.18" }
miraland-ledger = { path = "../ledger", version = "1.14.18" }
miraland-logger = { path = "../logger", version = "1.14.18" }
miraland-measure = { path = "../measure", version = "1.14.18" }
miraland-runtime = { path = "../runtime", version = "1.14.18" }
miraland-sdk = { path = "../sdk", version = "1.14.18" }
miraland-stake-program = { path = "../programs/stake", version = "1.14.18" }
miraland-storage-bigtable = { path = "../storage-bigtable", version = "1.14.18" }
miraland-transaction-status = { path = "../transaction-status", version = "1.14.18" }
miraland-version = { path = "../version", version = "1.14.18" }
miraland-vote-program = { path = "../programs/vote", version = "1.14.18" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
assert_cmd = "=2.0"
bytecount = "0.6.2"
predicates-core = "=1.0.5"
predicates-tree = "=1.0.7"

[target."cfg(unix)".dependencies]
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
