[package]
name = "miraland-upload-perf"
version = "1.14.17"
description = "Metrics Upload Utility"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
edition = "2021"
homepage = "https://miraland.top/"
publish = false

[dependencies]
miraland-metrics = { path = "../metrics", version = "=1.14.17" }
serde_json = "1.0.81"

[[bin]]
name = "miraland-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
