[package]
name = "miraland-bpf-rust-simulation"
version = "1.14.17-rc3"
description = "Miraland BPF Program Simulation Differences"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-bpf-rust-simulation"
edition = "2021"

[features]
test-bpf = []

[dependencies]
miraland-program = { path = "../../../../sdk/program", version = "=1.14.17-rc3" }

[dev-dependencies]
miraland-logger = { path = "../../../../logger", version = "=1.14.17-rc3" }
miraland-program-test = { path = "../../../../program-test", version = "=1.14.17-rc3" }
miraland-sdk = { path = "../../../../sdk", version = "=1.14.17-rc3" }
miraland-validator = { path = "../../../../validator", version = "=1.14.17-rc3" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
