[package]
name = "miraland-system-program"
description = "Miraland System program"
documentation = "https://docs.rs/miraland-system-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
miraland-program-runtime = { workspace = true }
miraland-sdk = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
miraland-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_system_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
