[package]
name = "miraland-send-transaction-service"
description = "Miraland send transaction service"
documentation = "https://docs.rs/miraland-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
miraland-client = { workspace = true }
miraland-measure = { workspace = true }
miraland-metrics = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-tpu-client = { workspace = true }

[dev-dependencies]
miraland-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
