[package]
name = "miraland-send-transaction-service"
version = "1.14.17"
description = "Miraland send transaction service"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.17"
miraland-client = { path = "../client", version = "=1.14.17" }
miraland-measure = { path = "../measure", version = "=1.14.17" }
miraland-metrics = { path = "../metrics", version = "=1.14.17" }
miraland-runtime = { path = "../runtime", version = "=1.14.17" }
miraland-sdk = { path = "../sdk", version = "=1.14.17" }

[dev-dependencies]
miraland-logger = { path = "../logger", version = "=1.14.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
