[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
edition = "2021"
name = "miraland-store-tool"
description = "Tool to inspect append vecs"
version = "1.14.18"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
publish = false

[dependencies]
clap = "2.33.1"
log = { version = "0.4.17" }
miraland-logger = { path = "../../logger", version = "1.14.18" }
miraland-runtime = { path = "..", version = "1.14.18" }
miraland-version = { path = "../../version", version = "1.14.18" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
