[package]
name = "miraland-poh"
version = "1.14.17"
description = "Miraland PoH"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-poh"
edition = "2021"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.17"
miraland-entry = { path = "../entry", version = "1.14.17" }
miraland-ledger = { path = "../ledger", version = "1.14.17" }
miraland-measure = { path = "../measure", version = "1.14.17" }
miraland-metrics = { path = "../metrics", version = "1.14.17" }
miraland-runtime = { path = "../runtime", version = "1.14.17" }
miraland-sdk = { path = "../sdk", version = "1.14.17" }
miraland-sys-tuner = { path = "../sys-tuner", version = "1.14.17" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
miraland-logger = { path = "../logger", version = "1.14.17" }
miraland-perf = { path = "../perf", version = "1.14.17" }
rand = "0.7.0"

[lib]
crate-type = ["lib"]
name = "miraland_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
