[package]
name = "miraland-vote-program"
version = "1.14.19"
description = "Miraland Vote program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-vote-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
miraland-frozen-abi = { path = "../../frozen-abi", version = "1.14.19" }
miraland-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "1.14.19" }
miraland-metrics = { path = "../../metrics", version = "1.14.19" }
miraland-program-runtime = { path = "../../program-runtime", version = "1.14.19" }
miraland-sdk = { path = "../../sdk", version = "1.14.19" }
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.138"
serde_derive = "1.0.103"
thiserror = "1.0"

[dev-dependencies]
itertools = "0.10.3"
miraland-logger = { path = "../../logger", version = "1.14.19" }
rand = "0.7.0"
test-case = "2.1.0"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
