[package]
name = "miraland-metrics"
version = "1.14.17-rc7"
description = "Miraland Metrics"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.foundation>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-metrics"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
gethostname = "0.2.3"
lazy_static = "1.4.0"
log = "0.4.17"
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc7" }
reqwest = { version = "=0.11.11", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }

[dev-dependencies]
env_logger = "0.9.0"
rand = "0.7.0"
serial_test = "0.8.0"

[lib]
name = "miraland_metrics"

[[bench]]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
